# define
## ini
PATH_INI = "./config.ini"
### discord id
SEC_ID = "ID"
KEY_TOKEN = "TOKEN"
KEY_ID_EVERYONE = "ID_EVERYONE"
KEY_ID_CH_NOTIFY = "ID_NOTIFY_CHANNEL"
KEY_ID_CH_ALLOWED = "ALLOWED_CHANNELS"
### redis
SEC_REDIS = "REDIS"
KEY_REDIS_URL = "URL"
RKEY_QUEUE = "KEY_QUEUE"
RKEY_LAST_UPDATE = "KEY_LAST_UPDATE"